# Generated by Django 4.0.6 on 2022-07-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('capacity', models.IntegerField()),
                ('unit_type', models.CharField(choices=[('1', 'LITRES'), ('2', 'GALLONS')], default='1', max_length=15)),
                ('water_type', models.CharField(choices=[('1', 'FRESH'), ('2', 'SALT'), ('3', 'BRACKISH')], default='1', max_length=15)),
            ],
        ),
    ]
